# Generated by Django 5.2.9 on 2026-01-27 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PillInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('usage', models.TextField()),
                ('dosage', models.TextField()),
                ('side_effects', models.TextField(blank=True)),
                ('precautions', models.TextField(blank=True)),
            ],
        ),
    ]
