# Generated by Django 5.2.9 on 2026-01-27 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_pillinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pillinfo',
            name='consumption_time',
            field=models.CharField(blank=True, help_text='e.g., Morning, Night, As needed', max_length=100),
        ),
        migrations.AddField(
            model_name='pillinfo',
            name='food_relation',
            field=models.CharField(blank=True, help_text='e.g., Before food, After food, With food', max_length=100),
        ),
    ]
